In [3]:
import random
import numpy as np
import datetime

data1 = [[random.randint(0,99) for j in range(1000)] for i in range(1000)]
count = 0

start_time = datetime.datetime.now()
for i in range(1000):
    for j in range(1000):
        if data1[i][j] > 50:
            count += 1

end_time = datetime.datetime.now()
print(count)
print('time of list: ',(end_time-start_time).microseconds)

data2 = np.array(data1)

start_time = datetime.datetime.now()
count = np.sum(data2 > 50)
end_time = datetime.datetime.now()
print(count)
print('time of list: ',(end_time-start_time).microseconds)

488683
time of list:  174765
488683
time of list:  2398


In [8]:
import numpy as np

a=np.array([[3,4],[5,6]])
b=np.array([[5,6],[7,8]])

print(a)
print(b)

print(a*b)
print(a+b)
print(a-b)
print(a/b)

c=np.array([[1,2,3],[4,5,6]])
d=np.array([[1,0,1]])

# array d will automatic boardcasting [[1,0,1],[1,0,1]]
print(c+d)

#dot product
print(a.dot(b))

[[3 4]
 [5 6]]
[[5 6]
 [7 8]]
[[15 24]
 [35 48]]
[[ 8 10]
 [12 14]]
[[-2 -2]
 [-2 -2]]
[[0.6        0.66666667]
 [0.71428571 0.75      ]]
[[2 2 4]
 [5 5 7]]
[[43 50]
 [67 78]]


In [ ]:
import numpy as np
d=np.loadtxt('sample_data.csv',delimiter=',',skiprows=1,usecols=(1,2,3,4,5))
print(d)
print(np.sum(d,axis=1))
print(d.dot(np.ones((5,1))))

prices=np.array([[20,10,50,90]])
print(prices.dot(d))
print(d.dot(np.ones((5,1)))*prices.T)